### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by LewisTehMinerz** [FrostOS-Team/FrostOS#10]
Just wondering, is this project dead? I haven't seen any activity but my own. I don't mind if your testing it in an emulator before publishing it. Is that why?
![18360-doge-doge-simple](https://cloud.githubusercontent.com/assets/4512372/13676152/e716cec6-e6e4-11e5-8be6-ca2838fa8568.jpg)

**Comment by MultHub** [comment]
it is dead, and remove the local in `local function sha256` in apis/SHA-256.lua, AND rename SHA-256.lua to sha256.lua

**Comment by Ale32bit** [comment]
I think the project is dead.
Rename and fix sha256 is useless

**Comment by MultHub** [comment]
>Rename and fix sha256 is useless

true, closing

**Comment by LewisTehMinerz** [comment]
Well, we'll need to restart the project again... it just died without any warning.

**Comment by MultHub** [comment]
>without any warning

true, closing

oh wait

**Comment by MultHub** [comment]
RANDOM IDEA: just remake FrostOS

as a fork of https://github.com/MultHub/Aurora EHEHEHEHEHHEHEHEHHEHEHEHEHEHEHHEHEHEHEHEHEHEHEHEH

**Comment by Ale32bit** [comment]
Nope, just remake it

**Comment by MultHub** [comment]
ask lewis
![18360-doge-doge-simple](https://cloud.githubusercontent.com/assets/4512372/13676152/e716cec6-e6e4-11e5-8be6-ca2838fa8568.jpg)

**Comment by Ale32bit** [comment]
Not again...

**Comment by MultHub** [comment]
k
![18360-doge-doge-simple](https://cloud.githubusercontent.com/assets/4512372/13676152/e716cec6-e6e4-11e5-8be6-ca2838fa8568.jpg)
![18360-doge-doge-simple](https://cloud.githubusercontent.com/assets/4512372/13676152/e716cec6-e6e4-11e5-8be6-ca2838fa8568.jpg)
![18360-doge-doge-simple](https://cloud.githubusercontent.com/assets/4512372/13676152/e716cec6-e6e4-11e5-8be6-ca2838fa8568.jpg)

**Comment by LewisTehMinerz** [comment]
We're continuing it, where we left off.
